spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cardsdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

app:
  encryption:
    key: ${ENCRYPTION_KEY:12345678901234567890123456789012}