spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cardsdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  jackson:
    property-naming-strategy: SNAKE_CASE

app:
  encryption:
    key: ${ENCRYPTION_KEY:12345678901234567890123456789012}